/**
 * Library。UI/UX §10。
 *
 * ファイルブラウザではなく **Artifact memory**。
 * 「どこに保存された？」を探させないのが役割なので、
 * どの仕事から生まれたか（lineage）を必ず辿れるようにする。
 */
import { useMemo, useState, type ReactElement } from 'react';
import { ArtifactType, type Artifact } from '@astra/contracts';
import type { AstraClient } from '@astra/api-client';
import { ArtifactShareState } from '../library/ShareState.js';
import { ArtifactActions } from '../library/ArtifactActions.js';
import {
  DATE_RANGES,
  EMPTY_FILTERS,
  activeFilterCount,
  filterOptions,
  generatedByLabel,
  lineageOf,
  matchesFilters,
  type LibraryFilters,
} from '../library/filters.js';
import type { TaskView } from '@astra/api-client';
import '../library/library.css';

/** §10.1 の Type chips。 */
export const LIBRARY_TYPE_CHIPS = [
  { id: 'ALL', label: 'すべて' },
  { id: 'MEETING_BUNDLE', label: '会議' },
  { id: 'REPORT', label: 'レポート' },
  { id: 'DOCUMENT', label: '資料' },
  { id: 'IMAGE', label: '画像' },
  { id: 'VIDEO', label: '動画' },
  { id: 'OTHER', label: 'その他' },
] as const;

export type LibraryChip = (typeof LIBRARY_TYPE_CHIPS)[number]['id'];

/** 種類の名前。chip と同じ表を使い、`MEETING_BUNDLE` を画面に出さない。 */
export function typeLabel(type: string): string {
  return LIBRARY_TYPE_CHIPS.find((chip) => chip.id === type)?.label ?? 'その他';
}

/** §10.1 / §22: 機密は色だけでなく文字で。**内部の識別子ではなく、意味を書く。** */
const SENSITIVITY_LABEL: Readonly<Record<string, string>> = {
  CONFIDENTIAL: '社外秘',
  REGULATED: '規制対象',
  PRIVATE: '',
};

/** chip に載っていない type は「その他」へ寄せる。取りこぼしを作らない。 */
export function matchesChip(type: Artifact['type'], chip: LibraryChip): boolean {
  if (chip === 'ALL') return true;
  if (chip === 'OTHER') {
    const named = LIBRARY_TYPE_CHIPS.map((c) => c.id).filter(
      (id) => id !== 'ALL' && id !== 'OTHER',
    ) as readonly string[];
    return !named.includes(type);
  }
  return type === chip;
}

export function LibraryPage({
  artifacts = [],
  tasks = [],
  selectedId = null,
  client = null,
  onSelect,
  onOpenTask,
}: {
  artifacts?: readonly Artifact[];
  /** 「Produced by: A社 商談準備」のため。無ければ id で辿るだけになる。 */
  tasks?: readonly TaskView[];
  selectedId?: string | null;
  /** 共有の状態を引く先。無ければ「確認しています」のまま（オフとは言わない）。 */
  client?: AstraClient | null;
  onSelect?(artifactId: string): void;
  onOpenTask?(taskId: string): void;
}): ReactElement {
  const [chip, setChip] = useState<LibraryChip>('ALL');
  // 共有を作ったら header の状態を引き直す（§10.2 常時可視化）
  const [shareRevision, setShareRevision] = useState(0);
  const [query, setQuery] = useState('');
  // §10.1 Filters: Project / Person / Date / Generated by / Sensitivity
  const [filters, setFilters] = useState<LibraryFilters>(EMPTY_FILTERS);
  const [lineageOpen, setLineageOpen] = useState(false);
  const options = useMemo(() => filterOptions(artifacts), [artifacts]);

  const visible = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return artifacts.filter(
      (a) =>
        matchesChip(a.type, chip) &&
        matchesFilters(a, filters) &&
        (needle.length === 0 || a.title.toLowerCase().includes(needle)),
    );
  }, [artifacts, chip, query, filters]);

  const selected = artifacts.find((a) => a.id === selectedId) ?? null;
  const taskTitle = (id: string | null): string | null =>
    id ? (tasks.find((t) => t.id === id)?.title ?? null) : null;
  const lineage = useMemo(
    () => (selected ? lineageOf(selected, artifacts) : []),
    [selected, artifacts],
  );
  const set = <K extends keyof LibraryFilters>(key: K, value: LibraryFilters[K]): void =>
    setFilters((current) => ({ ...current, [key]: value }));

  return (
    <section className="astra-library" aria-label="ライブラリ">
      <div className="astra-library__controls">
        <label className="astra-library__search">
          <span className="astra-visually-hidden">成果物を検索</span>
          <input
            type="search"
            // §10.1: 自然文で探せることを示す
            placeholder="先月のA社の決定事項"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />
        </label>
        <div className="astra-library__chips" role="group" aria-label="種類">
          {LIBRARY_TYPE_CHIPS.map((option) => (
            <button
              key={option.id}
              type="button"
              aria-pressed={chip === option.id}
              onClick={() => setChip(option.id)}
            >
              {option.label}
            </button>
          ))}
        </div>

        {/* §10.1 Filters。選択肢は手元の成果物から。無いものは「まだありません」と言う */}
        <div className="astra-library__filters" role="group" aria-label="絞り込み">
          <label>
            <span>プロジェクト</span>
            <select
              value={filters.project ?? ''}
              disabled={options.projects.length === 0}
              onChange={(e) => set('project', e.target.value || null)}
            >
              <option value="">
                {options.projects.length === 0 ? 'まだありません' : 'すべて'}
              </option>
              {options.projects.map((p) => (
                <option key={p} value={p}>
                  {p}
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>人</span>
            <select
              value={filters.person ?? ''}
              disabled={options.people.length === 0}
              onChange={(e) => set('person', e.target.value || null)}
            >
              <option value="">{options.people.length === 0 ? 'まだありません' : 'すべて'}</option>
              {options.people.map((p) => (
                <option key={p} value={p}>
                  {p}
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>期間</span>
            <select
              value={filters.date}
              onChange={(e) => set('date', e.target.value as LibraryFilters['date'])}
            >
              {DATE_RANGES.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.label}
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>作った主体</span>
            <select
              value={filters.generatedBy ?? ''}
              onChange={(e) => set('generatedBy', e.target.value || null)}
            >
              <option value="">すべて</option>
              {options.generatedBy.map((g) => (
                <option key={g.id} value={g.id}>
                  {g.label}
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>機密</span>
            <select
              value={filters.sensitivity ?? ''}
              onChange={(e) =>
                set('sensitivity', (e.target.value || null) as LibraryFilters['sensitivity'])
              }
            >
              <option value="">すべて</option>
              {options.sensitivities.map((sv) => (
                <option key={sv} value={sv}>
                  {SENSITIVITY_LABEL[sv] ?? sv}
                </option>
              ))}
            </select>
          </label>
          {activeFilterCount(filters) > 0 && (
            <button
              type="button"
              className="astra-button astra-button--quiet"
              onClick={() => setFilters(EMPTY_FILTERS)}
            >
              絞り込みを外す（{activeFilterCount(filters)}）
            </button>
          )}
        </div>
      </div>

      <div className="astra-library__body">
        {visible.length === 0 ? (
          <p className="astra-empty">
            {artifacts.length === 0
              ? 'まだ成果物はありません。仕事を1つ頼むとここに残ります。'
              : '該当する成果物はありません。'}
          </p>
        ) : (
          <ul className="astra-library__grid">
            {visible.map((artifact) => (
              <li key={artifact.id}>
                <button
                  type="button"
                  className="astra-artifact"
                  aria-current={artifact.id === selectedId ? 'true' : undefined}
                  onClick={() => onSelect?.(artifact.id)}
                >
                  <span className="astra-artifact__title">{artifact.title}</span>
                  {/* §10.1 card metadata: type / date / source task / lineage summary */}
                  <span className="astra-artifact__meta">
                    {typeLabel(artifact.type)} ·{' '}
                    {new Date(artifact.created_at).toLocaleDateString('ja-JP')}
                    {artifact.version > 1 ? ` · v${artifact.version}` : ''}
                  </span>
                  {(taskTitle(artifact.source_task_id) || artifact.parent_artifact_id) && (
                    <span className="astra-artifact__lineage">
                      {taskTitle(artifact.source_task_id)
                        ? `仕事: ${taskTitle(artifact.source_task_id)}`
                        : artifact.source_task_id
                          ? '仕事から'
                          : ''}
                      {artifact.parent_artifact_id ? ' · 派生' : ''}
                    </span>
                  )}
                  {/* §5.2 と同じ考え方: 機密は色だけでなく文字でも示す */}
                  {artifact.sensitivity !== 'PRIVATE' && (
                    <span className="astra-artifact__flag">
                      {SENSITIVITY_LABEL[artifact.sensitivity] ?? artifact.sensitivity}
                    </span>
                  )}
                </button>
              </li>
            ))}
          </ul>
        )}

        {selected && (
          <aside className="astra-library__preview" aria-label="プレビュー">
            <h3 className="astra-library__preview-title">{selected.title}</h3>
            <dl className="astra-library__facts">
              <dt>種類</dt>
              <dd>{typeLabel(selected.type)}</dd>
              <dt>作成</dt>
              <dd>{new Date(selected.created_at).toLocaleString('ja-JP')}</dd>
              <dt>版</dt>
              <dd>v{selected.version}</dd>
            </dl>

            {/* §10.2 Lineage: Derived from … / Produced by … / [View lineage] */}
            <section className="astra-lineage" aria-label="来歴">
              <h4>来歴</h4>
              <dl className="astra-lineage__facts">
                <dt>元にしたもの</dt>
                <dd>
                  {lineage.length === 0
                    ? selected.source_meeting_id
                      ? '会議の記録'
                      : '—'
                    : lineage.map((a) => `${a.title} v${a.version}`).join(' · ')}
                </dd>
                <dt>作った仕事</dt>
                <dd>
                  {selected.source_task_id ? (
                    <button
                      type="button"
                      className="astra-lineage__link"
                      onClick={() => onOpenTask?.(selected.source_task_id!)}
                    >
                      {taskTitle(selected.source_task_id) ?? 'この仕事'}
                    </button>
                  ) : (
                    generatedByLabel(selected.source_agent_id)
                  )}
                </dd>
              </dl>
              {lineage.length > 0 && (
                <button
                  type="button"
                  className="astra-button astra-button--quiet"
                  aria-expanded={lineageOpen}
                  onClick={() => setLineageOpen((o) => !o)}
                >
                  View lineage
                </button>
              )}
              {lineageOpen && (
                <ol className="astra-lineage__chain" aria-label="派生の元をたどる">
                  <li aria-current="true">
                    {selected.title} v{selected.version}
                  </li>
                  {lineage.map((a) => (
                    <li key={a.id}>
                      <button
                        type="button"
                        className="astra-lineage__link"
                        onClick={() => onSelect?.(a.id)}
                      >
                        {a.title} v{a.version}
                      </button>
                      <span className="astra-lineage__when">
                        {new Date(a.created_at).toLocaleDateString('ja-JP')}
                      </span>
                    </li>
                  ))}
                </ol>
              )}
            </section>

            {/* §10.1: download / share は preview から */}
            <ArtifactActions
              client={client}
              artifact={selected}
              onShared={() => setShareRevision((r) => r + 1)}
            />

            {/* §10.2: Share は既定 OFF。**実際の状態**を header に常時可視化する */}
            <ArtifactShareState
              client={client}
              artifactId={selected.id}
              refreshKey={shareRevision}
            />
          </aside>
        )}
      </div>
    </section>
  );
}

export { ArtifactType };
