// @generated by scripts/gen-shortcuts.mjs — do not edit.
//
// 正は packages/ui-kit/src/shortcuts.ts（UI/UX §20）。
// 表を変えるときはそちらを直して `pnpm gen:shortcuts` を実行する。

use tauri_plugin_global_shortcut::{Code, Modifiers, Shortcut};

/// 1 つの割り当て。
#[derive(Debug, Clone, Copy)]
pub struct Binding {
    pub modifiers: Option<Modifiers>,
    pub code: Code,
    /// TypeScript 側と突き合わせるための `KeyboardEvent.code`。
    pub label: &'static str,
}

impl Binding {
    pub fn shortcut(self) -> Shortcut {
        Shortcut::new(self.modifiers, self.code)
    }
}

/// OS 全体で効くショートカット（UI/UX §20 の global 行）。
#[derive(Debug, Clone, Copy)]
pub struct GlobalShortcutSpec {
    pub id: &'static str,
    pub label: &'static str,
    /// 押している間だけ効くもの（push-to-talk）。
    pub hold: bool,
    pub default_binding: Binding,
    /// 既定が OS / IME に取られているときに薦める順の候補。
    pub alternates: &'static [Binding],
}

#[cfg(target_os = "macos")]
pub const GLOBAL_SHORTCUTS: &[GlobalShortcutSpec] = &[
    GlobalShortcutSpec {
        id: "dock.toggle",
        label: "Task Dock を開く / 閉じる",
        hold: false,
        default_binding: Binding {
            modifiers: Some(Modifiers::from_bits_truncate(Modifiers::ALT.bits())),
            code: Code::Space,
            label: "Space",
        },
        alternates: &[
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::SHIFT.bits(),
                )),
                code: Code::Space,
                label: "Space",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::SHIFT.bits() | Modifiers::SUPER.bits(),
                )),
                code: Code::KeyJ,
                label: "KeyJ",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::SUPER.bits(),
                )),
                code: Code::Period,
                label: "Period",
            },
        ],
    },
    GlobalShortcutSpec {
        id: "dock.pushToTalk",
        label: "押している間だけ話す",
        hold: true,
        default_binding: Binding {
            modifiers: Some(Modifiers::from_bits_truncate(Modifiers::ALT.bits())),
            code: Code::KeyD,
            label: "KeyD",
        },
        alternates: &[
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::SHIFT.bits(),
                )),
                code: Code::KeyD,
                label: "KeyD",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(Modifiers::ALT.bits())),
                code: Code::Backquote,
                label: "Backquote",
            },
        ],
    },
];

#[cfg(target_os = "windows")]
pub const GLOBAL_SHORTCUTS: &[GlobalShortcutSpec] = &[
    GlobalShortcutSpec {
        id: "dock.toggle",
        label: "Task Dock を開く / 閉じる",
        hold: false,
        default_binding: Binding {
            modifiers: Some(Modifiers::from_bits_truncate(
                Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
            )),
            code: Code::Space,
            label: "Space",
        },
        alternates: &[
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::SHIFT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::Space,
                label: "Space",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::KeyJ,
                label: "KeyJ",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::Period,
                label: "Period",
            },
        ],
    },
    GlobalShortcutSpec {
        id: "dock.pushToTalk",
        label: "押している間だけ話す",
        hold: true,
        default_binding: Binding {
            modifiers: Some(Modifiers::from_bits_truncate(
                Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
            )),
            code: Code::KeyD,
            label: "KeyD",
        },
        alternates: &[
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::SHIFT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::KeyD,
                label: "KeyD",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(Modifiers::CONTROL.bits())),
                code: Code::Backquote,
                label: "Backquote",
            },
        ],
    },
];

#[cfg(not(any(target_os = "macos", target_os = "windows")))]
pub const GLOBAL_SHORTCUTS: &[GlobalShortcutSpec] = &[
    GlobalShortcutSpec {
        id: "dock.toggle",
        label: "Task Dock を開く / 閉じる",
        hold: false,
        default_binding: Binding {
            modifiers: Some(Modifiers::from_bits_truncate(
                Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
            )),
            code: Code::Space,
            label: "Space",
        },
        alternates: &[
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::SHIFT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::Space,
                label: "Space",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::KeyJ,
                label: "KeyJ",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::Period,
                label: "Period",
            },
        ],
    },
    GlobalShortcutSpec {
        id: "dock.pushToTalk",
        label: "押している間だけ話す",
        hold: true,
        default_binding: Binding {
            modifiers: Some(Modifiers::from_bits_truncate(
                Modifiers::ALT.bits() | Modifiers::CONTROL.bits(),
            )),
            code: Code::KeyD,
            label: "KeyD",
        },
        alternates: &[
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(
                    Modifiers::SHIFT.bits() | Modifiers::CONTROL.bits(),
                )),
                code: Code::KeyD,
                label: "KeyD",
            },
            Binding {
                modifiers: Some(Modifiers::from_bits_truncate(Modifiers::CONTROL.bits())),
                code: Code::Backquote,
                label: "Backquote",
            },
        ],
    },
];
