// @generated by scripts/gen-design-tokens.mjs — do not edit.
// 正は shared/design/tokens.json。値を変えたら `pnpm gen:design-tokens`。
import CoreGraphics

/// 手書き案の寸法（logical points）。両 OS 共通の数値を Swift へ生成したもの。
enum Metrics {
    static let workspaceWidth: CGFloat = 920
    static let workspaceHeight: CGFloat = 590
    static let workspaceRadius: CGFloat = 28
    static let notchWidth: CGFloat = 286
    static let notchDepth: CGFloat = 25
    static let notchShoulder: CGFloat = 30
    static let dockWidth: CGFloat = 250
    static let dockHeight: CGFloat = 42
    static let hudWidth: CGFloat = 310
    static let hudHeight: CGFloat = 31
    static let hudBottomRadius: CGFloat = 17
    static let paletteWidth: CGFloat = 140
    static let assistantWidth: CGFloat = 180
    static let paletteRadius: CGFloat = 12
}

/// 遷移の時間（秒）。
enum Motion {
    static let showMs: Double = 0.120
    static let hideMs: Double = 0.100
    static let drawerMs: Double = 0.180
}
