// <auto-generated by scripts/gen-design-tokens.mjs — do not edit.>
// 正は shared/design/tokens.json。値を変えたら `pnpm gen:design-tokens`。
namespace Astra;

/// <summary>手書き案の寸法（effective px）。両 OS 共通の数値を Windows へ生成したもの。</summary>
public static class Metrics
{
    public const double WorkspaceWidth = 920;
    public const double WorkspaceHeight = 590;
    public const double WorkspaceRadius = 28;
    public const double NotchWidth = 286;
    public const double NotchDepth = 25;
    public const double NotchShoulder = 30;
    public const double DockWidth = 250;
    public const double DockHeight = 42;
    public const double HudWidth = 310;
    public const double HudHeight = 31;
    public const double HudBottomRadius = 17;
    public const double PaletteWidth = 140;
    public const double AssistantWidth = 180;
    public const double PaletteRadius = 12;
}

/// <summary>遷移の時間（ミリ秒）。</summary>
public static class Motion
{
    public const int ShowMs = 120;
    public const int HideMs = 100;
    public const int DrawerMs = 180;
}
