#!/usr/bin/env bash
# schema.sql を生成する。
#
# dbmate の --schema-file には任せない。ホストの pg_dump がサーバより古いと
# **失敗しても終了コード 0 のまま**で、生成物が黙って古いまま残る（実際に踏んだ）。
# ここでは版を突き合わせ、合わなければ止まるか、コンテナ側の pg_dump を使う。
#
#   ./scripts/dump-schema.sh <database-url> <output-file>
set -euo pipefail

URL="${1:?database url required}"
OUT="${2:?output file required}"

server_major() {
  psql "$URL" -X -t -A -c 'show server_version_num' | cut -c1-2
}

local_major() {
  pg_dump --version | sed -E 's/.* ([0-9]+)\..*/\1/'
}

SERVER="$(server_major)"

dump_with_local() {
  pg_dump --schema-only --no-owner --no-privileges --no-comments "$URL"
}

# サーバと同じ版の pg_dump を持つコンテナを探す。
# ホストに合う版を入れさせるより、既に動いているコンテナを使う方が確実。
container_for_url() {
  command -v docker >/dev/null 2>&1 || return 1
  local port
  port="$(printf '%s' "$URL" | sed -E 's#.*:([0-9]+)/.*#\1#')"
  docker ps --format '{{.Names}} {{.Ports}}' 2>/dev/null \
    | awk -v p=":$port->" '$0 ~ p {print $1; exit}'
}

dump_with_container() {
  local name="$1" body
  # コンテナ内からは常に自分自身なので localhost:5432 で足りる
  body="$(printf '%s' "$URL" | sed -E 's#^postgres://([^@]*)@[^/]+/#postgres://\1@localhost:5432/#')"
  docker exec -i "$name" pg_dump --schema-only --no-owner --no-privileges --no-comments "$body"
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if [ "$(local_major)" -ge "$SERVER" ]; then
  dump_with_local > "$TMP"
else
  CONTAINER="$(container_for_url || true)"
  if [ -z "$CONTAINER" ]; then
    echo "FAIL: local pg_dump is $(local_major) but the server is $SERVER, and no matching container was found." >&2
    echo "      Install a pg_dump >= $SERVER, or run the database through infra/docker-compose.dev.yml." >&2
    exit 1
  fi
  echo "using pg_dump inside container $CONTAINER (local pg_dump is $(local_major), server is $SERVER)" >&2
  dump_with_container "$CONTAINER" > "$TMP"
fi

# 空 / 極端に短い出力は失敗とみなす。黙って空ファイルを置かない。
if [ "$(wc -l < "$TMP")" -lt 50 ]; then
  echo "FAIL: the dump looks truncated ($(wc -l < "$TMP") lines)." >&2
  exit 1
fi

# 実行のたびに変わる行を落とす。残すと生成物の鮮度検査が毎回落ちる。
#   \restrict / \unrestrict … pg_dump 16 以降が付ける乱数トークン
#   Dumped from / Dumped by   … サーバと pg_dump の版（環境で変わる）
normalize() {
  grep -v -E '^\\(un)?restrict ' | grep -v -E '^-- Dumped (from|by) '
}

{
  echo "-- @generated by scripts/dump-schema.sh — do not edit."
  echo "-- 正は infra/db/migrations/*.sql（ADR 0002）。変更は 'pnpm db:migrate' で反映する。"
  echo
  normalize < "$TMP"
  echo
  echo "-- dbmate が適用済みとみなす移行"
  psql "$URL" -X -t -A -c \
    "select 'INSERT INTO schema_migrations (version) VALUES ('''||version||''');' from schema_migrations order by version"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, server major $SERVER)"
