// @generated by scripts/gen-dock-geometry.mjs — do not edit.
//
// 正は packages/ui-kit/src/tokens/dock.ts（UI/UX §4.1・§4.2）。
// 値を変えるときはそちらを直して `pnpm gen:dock-geometry` を実行する。

/// Dock が形を変える状態（UI/UX §3・§4.1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum DockState {
    Ready,
    Typing,
    Listening,
    ContextPeek,
    Working,
}

/// window のサイズ。高さは内容に応じて min..=max の範囲で決める。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DockSize {
    pub width: u32,
    pub min_height: u32,
    pub max_height: u32,
}

impl DockState {
    pub fn size(self) -> DockSize {
        match self {
            DockState::Ready => DockSize {
                width: 560,
                min_height: 56,
                max_height: 56,
            },
            DockState::Typing => DockSize {
                width: 640,
                min_height: 96,
                max_height: 140,
            },
            DockState::Listening => DockSize {
                width: 560,
                min_height: 96,
                max_height: 96,
            },
            DockState::ContextPeek => DockSize {
                width: 640,
                min_height: 140,
                max_height: 220,
            },
            DockState::Working => DockSize {
                width: 620,
                min_height: 160,
                max_height: 520,
            },
        }
    }
}

/// 画面下端からの距離（UI/UX §4.2）。
pub const BOTTOM_OFFSET_MIN: i32 = 48;
pub const BOTTOM_OFFSET_MAX: i32 = 72;
pub const BOTTOM_OFFSET_DEFAULT: i32 = 56;
/// 画面端に寄せすぎないための余白。
pub const EDGE_MARGIN: i32 = 16;
