// @generated by scripts/gen-dock-geometry.mjs — do not edit.
//
// 正は packages/ui-kit/src/tokens/dock.ts（UI/UX §4.1・§4.2）。
// 値を変えるときはそちらを直して `pnpm gen:dock-geometry` を実行する。

/// Dock が形を変える状態（UI/UX §3・§4.1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum DockState {
    Idle,
    Pill,
    Menu,
    Ready,
    Typing,
    Listening,
    ContextPeek,
    Working,
    Recording,
    Processing,
}

/// window のサイズ。高さは内容に応じて min..=max の範囲で決める。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DockSize {
    pub width: u32,
    pub min_height: u32,
    pub max_height: u32,
}

/// 配置。上（メニューバー直下）か下（macOS Dock の少し上）か。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Placement {
    Top,
    Bottom,
}

impl DockState {
    pub fn size(self) -> DockSize {
        match self {
            DockState::Idle => DockSize {
                width: 310,
                min_height: 31,
                max_height: 31,
            },
            DockState::Pill => DockSize {
                width: 360,
                min_height: 40,
                max_height: 40,
            },
            DockState::Menu => DockSize {
                width: 320,
                min_height: 156,
                max_height: 156,
            },
            DockState::Ready => DockSize {
                width: 560,
                min_height: 56,
                max_height: 56,
            },
            DockState::Typing => DockSize {
                width: 640,
                min_height: 96,
                max_height: 140,
            },
            DockState::Listening => DockSize {
                width: 560,
                min_height: 96,
                max_height: 96,
            },
            DockState::ContextPeek => DockSize {
                width: 640,
                min_height: 140,
                max_height: 220,
            },
            DockState::Working => DockSize {
                width: 620,
                min_height: 160,
                max_height: 520,
            },
            DockState::Recording => DockSize {
                width: 320,
                min_height: 44,
                max_height: 320,
            },
            DockState::Processing => DockSize {
                width: 260,
                min_height: 36,
                max_height: 36,
            },
        }
    }

    /// 録音のときだけ下へ降りる。それ以外は上に留まる。
    pub fn placement(self) -> Placement {
        match self {
            DockState::Idle => Placement::Top,
            DockState::Pill => Placement::Top,
            DockState::Menu => Placement::Top,
            DockState::Ready => Placement::Top,
            DockState::Typing => Placement::Top,
            DockState::Listening => Placement::Top,
            DockState::ContextPeek => Placement::Top,
            DockState::Working => Placement::Top,
            DockState::Recording => Placement::Bottom,
            DockState::Processing => Placement::Bottom,
        }
    }
}

/// 画面下端からの距離（UI/UX §4.2）。
pub const BOTTOM_OFFSET_MIN: i32 = 48;
pub const BOTTOM_OFFSET_MAX: i32 = 72;
pub const BOTTOM_OFFSET_DEFAULT: i32 = 56;
/// 録音中の Recording Dock の、画面下端からの距離。
pub const RECORDING_BOTTOM_OFFSET: i32 = 68;
/// 上部ピルの、作業領域上端からの距離。
pub const TOP_OFFSET: i32 = 0;
/// 画面端に寄せすぎないための余白。
pub const EDGE_MARGIN: i32 = 16;
