// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_CLONE_RECORDINGSESSION
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_CLONE_RECORDINGSESSION
void*_Nonnull uniffi_astra_core_fn_clone_recordingsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FREE_RECORDINGSESSION
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FREE_RECORDINGSESSION
void uniffi_astra_core_fn_free_recordingsession(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_CONSTRUCTOR_RECORDINGSESSION_START
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_CONSTRUCTOR_RECORDINGSESSION_START
void*_Nonnull uniffi_astra_core_fn_constructor_recordingsession_start(RustBuffer root, RustBuffer meeting_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_FINISH
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_FINISH
void uniffi_astra_core_fn_method_recordingsession_finish(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_MEETING_ID
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_MEETING_ID
RustBuffer uniffi_astra_core_fn_method_recordingsession_meeting_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_PUSH_SAMPLES
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_PUSH_SAMPLES
uint32_t uniffi_astra_core_fn_method_recordingsession_push_samples(void*_Nonnull ptr, RustBuffer samples, uint32_t sample_rate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_RECORDED_MS
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_RECORDED_MS
uint64_t uniffi_astra_core_fn_method_recordingsession_recorded_ms(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_SET_LINK
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_SET_LINK
void uniffi_astra_core_fn_method_recordingsession_set_link(void*_Nonnull ptr, RustBuffer link, uint64_t pending_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_SET_PAUSED
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_SET_PAUSED
void uniffi_astra_core_fn_method_recordingsession_set_paused(void*_Nonnull ptr, int8_t paused, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_METHOD_RECORDINGSESSION_SNAPSHOT
RustBuffer uniffi_astra_core_fn_method_recordingsession_snapshot(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_CREATE_MEETING
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_CREATE_MEETING
RustBuffer uniffi_astra_core_fn_func_api_create_meeting(RustBuffer base_url, RustBuffer access_token, RustBuffer title, RustBuffer language, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_DEV_SIGN_IN
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_DEV_SIGN_IN
RustBuffer uniffi_astra_core_fn_func_api_dev_sign_in(RustBuffer base_url, RustBuffer email, RustBuffer display_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_FINISH_MEETING
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_FINISH_MEETING
RustBuffer uniffi_astra_core_fn_func_api_finish_meeting(RustBuffer base_url, RustBuffer access_token, RustBuffer meeting_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_ME
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_ME
RustBuffer uniffi_astra_core_fn_func_api_me(RustBuffer base_url, RustBuffer access_token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_REACHABLE
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_REACHABLE
int8_t uniffi_astra_core_fn_func_api_reachable(RustBuffer base_url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_UPLOAD_MEETING_AUDIO
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_API_UPLOAD_MEETING_AUDIO
uint64_t uniffi_astra_core_fn_func_api_upload_meeting_audio(RustBuffer base_url, RustBuffer access_token, RustBuffer meeting_id, RustBuffer journal_root, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_ASTRA_CORE_VERSION
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_ASTRA_CORE_VERSION
RustBuffer uniffi_astra_core_fn_func_astra_core_version(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_FORMAT_ELAPSED
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_FORMAT_ELAPSED
RustBuffer uniffi_astra_core_fn_func_format_elapsed(uint64_t ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_RANK_CONTEXT
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_RANK_CONTEXT
RustBuffer uniffi_astra_core_fn_func_rank_context(RustBuffer query, RustBuffer candidates, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_RECORDING_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_RECORDING_SNAPSHOT
RustBuffer uniffi_astra_core_fn_func_recording_snapshot(RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_SCAN_RECOVERABLE
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_SCAN_RECOVERABLE
RustBuffer uniffi_astra_core_fn_func_scan_recoverable(RustBuffer root, RustBuffer active, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_TO_WIRE
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_FN_FUNC_TO_WIRE
RustBuffer uniffi_astra_core_fn_func_to_wire(RustBuffer samples, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_astra_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_astra_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_FREE
void ffi_astra_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_astra_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U8
void ffi_astra_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U8
void ffi_astra_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U8
void ffi_astra_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_astra_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I8
void ffi_astra_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I8
void ffi_astra_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I8
void ffi_astra_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_astra_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U16
void ffi_astra_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U16
void ffi_astra_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U16
void ffi_astra_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_astra_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I16
void ffi_astra_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I16
void ffi_astra_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I16
void ffi_astra_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_astra_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U32
void ffi_astra_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U32
void ffi_astra_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U32
void ffi_astra_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_astra_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I32
void ffi_astra_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I32
void ffi_astra_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I32
void ffi_astra_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_astra_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_U64
void ffi_astra_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_U64
void ffi_astra_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_U64
void ffi_astra_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_astra_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_I64
void ffi_astra_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_I64
void ffi_astra_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_I64
void ffi_astra_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_astra_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_F32
void ffi_astra_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_F32
void ffi_astra_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_F32
void ffi_astra_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_astra_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_F64
void ffi_astra_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_F64
void ffi_astra_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_F64
void ffi_astra_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_astra_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_POINTER
void ffi_astra_core_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_POINTER
void ffi_astra_core_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_POINTER
void ffi_astra_core_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_astra_core_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_astra_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_astra_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_astra_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_astra_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_POLL_VOID
void ffi_astra_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_astra_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_FREE_VOID
void ffi_astra_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_astra_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_CREATE_MEETING
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_CREATE_MEETING
uint16_t uniffi_astra_core_checksum_func_api_create_meeting(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_DEV_SIGN_IN
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_DEV_SIGN_IN
uint16_t uniffi_astra_core_checksum_func_api_dev_sign_in(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_FINISH_MEETING
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_FINISH_MEETING
uint16_t uniffi_astra_core_checksum_func_api_finish_meeting(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_ME
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_ME
uint16_t uniffi_astra_core_checksum_func_api_me(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_REACHABLE
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_REACHABLE
uint16_t uniffi_astra_core_checksum_func_api_reachable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_UPLOAD_MEETING_AUDIO
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_API_UPLOAD_MEETING_AUDIO
uint16_t uniffi_astra_core_checksum_func_api_upload_meeting_audio(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_ASTRA_CORE_VERSION
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_ASTRA_CORE_VERSION
uint16_t uniffi_astra_core_checksum_func_astra_core_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_FORMAT_ELAPSED
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_FORMAT_ELAPSED
uint16_t uniffi_astra_core_checksum_func_format_elapsed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_RANK_CONTEXT
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_RANK_CONTEXT
uint16_t uniffi_astra_core_checksum_func_rank_context(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_RECORDING_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_RECORDING_SNAPSHOT
uint16_t uniffi_astra_core_checksum_func_recording_snapshot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_SCAN_RECOVERABLE
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_SCAN_RECOVERABLE
uint16_t uniffi_astra_core_checksum_func_scan_recoverable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_TO_WIRE
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_FUNC_TO_WIRE
uint16_t uniffi_astra_core_checksum_func_to_wire(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_FINISH
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_FINISH
uint16_t uniffi_astra_core_checksum_method_recordingsession_finish(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_MEETING_ID
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_MEETING_ID
uint16_t uniffi_astra_core_checksum_method_recordingsession_meeting_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_PUSH_SAMPLES
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_PUSH_SAMPLES
uint16_t uniffi_astra_core_checksum_method_recordingsession_push_samples(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_RECORDED_MS
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_RECORDED_MS
uint16_t uniffi_astra_core_checksum_method_recordingsession_recorded_ms(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_SET_LINK
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_SET_LINK
uint16_t uniffi_astra_core_checksum_method_recordingsession_set_link(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_SET_PAUSED
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_SET_PAUSED
uint16_t uniffi_astra_core_checksum_method_recordingsession_set_paused(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_SNAPSHOT
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_METHOD_RECORDINGSESSION_SNAPSHOT
uint16_t uniffi_astra_core_checksum_method_recordingsession_snapshot(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_CONSTRUCTOR_RECORDINGSESSION_START
#define UNIFFI_FFIDEF_UNIFFI_ASTRA_CORE_CHECKSUM_CONSTRUCTOR_RECORDINGSESSION_START
uint16_t uniffi_astra_core_checksum_constructor_recordingsession_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASTRA_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ASTRA_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_astra_core_uniffi_contract_version(void
    
);
#endif

